/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'replyToText' : [] | [string],
  'userName' : string,
  'userRank' : string,
  'edited' : boolean,
  'userId' : string,
  'text' : string,
  'timestamp' : bigint,
  'replyToId' : [] | [bigint],
}
export type Rank = { 'VIP' : null } |
  { 'Employee' : null } |
  { 'Admin' : null } |
  { 'Friend' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'id' : string,
  'name' : string,
  'rank' : Rank,
  'lastSeen' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'askAI' : ActorMethod<[string], string>,
  'assignRank' : ActorMethod<[string, string, Rank], boolean>,
  'banUser' : ActorMethod<[string, string, bigint, string], boolean>,
  'checkBan' : ActorMethod<
    [string],
    { 'expiresAt' : bigint, 'banned' : boolean, 'reason' : string }
  >,
  'deleteMessage' : ActorMethod<[string, bigint], boolean>,
  'editMessage' : ActorMethod<[string, bigint, string], boolean>,
  'forceAdminRank' : ActorMethod<[string], boolean>,
  'getDMs' : ActorMethod<[string, string], Array<Message>>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getSplash' : ActorMethod<[], string>,
  'getUserRank' : ActorMethod<[string], string>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getVersionString' : ActorMethod<[], string>,
  'isKicked' : ActorMethod<[string], boolean>,
  'kickUser' : ActorMethod<[string, string], boolean>,
  'registerUser' : ActorMethod<[string], string>,
  'sendDM' : ActorMethod<[string, string, string], bigint>,
  'sendMessage' : ActorMethod<
    [string, string, [] | [bigint], [] | [string]],
    bigint
  >,
  'setAccessCode' : ActorMethod<[string, string], boolean>,
  'setSplash' : ActorMethod<[string, string], boolean>,
  'setVersionString' : ActorMethod<[string, string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLastSeen' : ActorMethod<[string], undefined>,
  'verifyCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];