/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Rank = IDL.Variant({
  'Employee' : IDL.Null,
  'Admin' : IDL.Null,
  'Friend' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'userRank' : IDL.Text,
  'userId' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'rank' : Rank,
  'lastSeen' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'askAI' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignRank' : IDL.Func([IDL.Text, IDL.Text, Rank], [IDL.Bool], []),
  'getDMs' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMessages' : IDL.Func([IDL.Int], [IDL.Vec(Message)], ['query']),
  'getUserRank' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [IDL.Text], []),
  'sendDM' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLastSeen' : IDL.Func([IDL.Text], [], []),
  'verifyCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Rank = IDL.Variant({
    'Employee' : IDL.Null,
    'Admin' : IDL.Null,
    'Friend' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'userRank' : IDL.Text,
    'userId' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'rank' : Rank,
    'lastSeen' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'askAI' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignRank' : IDL.Func([IDL.Text, IDL.Text, Rank], [IDL.Bool], []),
    'getDMs' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMessages' : IDL.Func([IDL.Int], [IDL.Vec(Message)], ['query']),
    'getUserRank' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [IDL.Text], []),
    'sendDM' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLastSeen' : IDL.Func([IDL.Text], [], []),
    'verifyCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };