/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface User {
    id: string;
    name: string;
    rank: Rank;
    lastSeen: bigint;
}
export interface Message {
    id: bigint;
    replyToText?: string;
    userName: string;
    userRank: string;
    edited: boolean;
    userId: string;
    text: string;
    timestamp: bigint;
    replyToId?: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Rank {
    VIP = "VIP",
    Employee = "Employee",
    Admin = "Admin",
    Friend = "Friend"
}
export interface backendInterface {
    askAI(prompt: string): Promise<string>;
    assignRank(adminUserId: string, targetUserId: string, rank: Rank): Promise<boolean>;
    banUser(adminUserId: string, targetUserId: string, durationMinutes: bigint, reason: string): Promise<boolean>;
    checkBan(userId: string): Promise<{
        expiresAt: bigint;
        banned: boolean;
        reason: string;
    }>;
    deleteMessage(adminUserId: string, messageId: bigint): Promise<boolean>;
    editMessage(adminUserId: string, messageId: bigint, newText: string): Promise<boolean>;
    getDMs(userId: string, _otherUserId: string): Promise<Array<Message>>;
    getMessages(since: bigint): Promise<Array<Message>>;
    getSplash(): Promise<string>;
    getUserRank(userId: string): Promise<string>;
    getUsers(): Promise<Array<User>>;
    isKicked(userId: string): Promise<boolean>;
    kickUser(adminUserId: string, targetUserId: string): Promise<boolean>;
    registerUser(name: string): Promise<string>;
    sendDM(fromUserId: string, toUserId: string, text: string): Promise<bigint>;
    sendMessage(userId: string, text: string, replyToId: bigint | null, replyToText: string | null): Promise<bigint>;
    setAccessCode(adminUserId: string, code: string): Promise<boolean>;
    setSplash(adminUserId: string, text: string): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateLastSeen(userId: string): Promise<void>;
    verifyCode(code: string): Promise<boolean>;
}
import type { Message as _Message, Rank as _Rank, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async askAI(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askAI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askAI(arg0);
            return result;
        }
    }
    async assignRank(arg0: string, arg1: string, arg2: Rank): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRank(arg0, arg1, to_candid_Rank_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRank(arg0, arg1, to_candid_Rank_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async banUser(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async checkBan(arg0: string): Promise<{
        expiresAt: bigint;
        banned: boolean;
        reason: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkBan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkBan(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0, arg1);
            return result;
        }
    }
    async editMessage(arg0: string, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async getDMs(arg0: string, arg1: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDMs(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDMs(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSplash(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSplash();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSplash();
            return result;
        }
    }
    async getUserRank(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRank(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRank(arg0);
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isKicked(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isKicked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isKicked(arg0);
            return result;
        }
    }
    async kickUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.kickUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kickUser(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async sendDM(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDM(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDM(arg0, arg1, arg2);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: bigint | null, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async setAccessCode(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccessCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccessCode(arg0, arg1);
            return result;
        }
    }
    async setSplash(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setSplash(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSplash(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateLastSeen(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeen(arg0);
            return result;
        }
    }
    async verifyCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCode(arg0);
            return result;
        }
    }
}
function from_candid_Message_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Rank_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rank): Rank {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_User_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    rank: _Rank;
    lastSeen: bigint;
}): {
    id: string;
    name: string;
    rank: Rank;
    lastSeen: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        rank: from_candid_Rank_n11(_uploadFile, _downloadFile, value.rank),
        lastSeen: value.lastSeen
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    replyToText: [] | [string];
    userName: string;
    userRank: string;
    edited: boolean;
    userId: string;
    text: string;
    timestamp: bigint;
    replyToId: [] | [bigint];
}): {
    id: bigint;
    replyToText?: string;
    userName: string;
    userRank: string;
    edited: boolean;
    userId: string;
    text: string;
    timestamp: bigint;
    replyToId?: bigint;
} {
    return {
        id: value.id,
        replyToText: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.replyToText)),
        userName: value.userName,
        userRank: value.userRank,
        edited: value.edited,
        userId: value.userId,
        text: value.text,
        timestamp: value.timestamp,
        replyToId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyToId))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VIP: null;
} | {
    Employee: null;
} | {
    Admin: null;
} | {
    Friend: null;
}): Rank {
    return "VIP" in value ? Rank.VIP : "Employee" in value ? Rank.Employee : "Admin" in value ? Rank.Admin : "Friend" in value ? Rank.Friend : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Rank_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rank): _Rank {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rank): {
    VIP: null;
} | {
    Employee: null;
} | {
    Admin: null;
} | {
    Friend: null;
} {
    return value == Rank.VIP ? {
        VIP: null
    } : value == Rank.Employee ? {
        Employee: null
    } : value == Rank.Admin ? {
        Admin: null
    } : value == Rank.Friend ? {
        Friend: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
